### ISSUE TITLE
Add Stacey Potter to Media/Events teams

### ISSUE THREAD

**Issue by staceypotter** [open-gitops/project#122]
I am interested in helping the project with upcoming socials and events. 
Not sure if I need sponsorship, but perhaps @scottrigby & @christianh814 would be interested? thx

- [x]  confirm GitHub username: staceypotter
- [x]  add to Media/Communications team
- [x]  add to Events GH team

**Comment by scottrigby** [comment]
We all discussed it, very happy to have your help!

For everyone: Stacey has been involved in the GitOps community long before the GitOps WG or OpenGitOps. Many of you may already know her as the event coordinator for [GitOpsDays](https://www.gitopsdays.com/), and is also a member of the [Flux community team](https://github.com/fluxcd/community/blob/main/COMMUNITY.md).

**Comment by christianh814** [comment]
Def happy to get her help! 👍🏽

**Comment by scottrigby** [comment]
Added to @open-gitops/media and @open-gitops/events. Thanks @staceypotter !

**Comment by scottrigby** [comment]
Added to [next meeting agenda]( https://docs.google.com/document/d/1hxifmCdOV5_FbKloDJRWZQHq0ge-trXJKF-BgV4wHVk/edit#heading=h.i7b0uuk94s93) to note this
