### ISSUE TITLE
Interest in joining the events team

### ISSUE THREAD

**Issue by niklasmtj** [open-gitops/project#144]
Since KubeCon Amsterdam and GitOpsCon coming closer I would like to volunteer to help the group with organizing these events. So I'd like to join the team. I have no experience in this type of scale but I'm organizing a small local meetup here in Cologne.

**Comment by scottrigby** [comment]
Hey @staceypotter, that's exactly right 👍

**Comment by scottrigby** [comment]
All set! @staceypotter I updated your checklist above. All complete, thanks!
