### ISSUE TITLE
Principle 3 - Pulled Automatically

### ISSUE THREAD

**Issue by kickthemooon** [open-gitops/project#162]
Correct me if I am wrong but when I think of GitOps I think of things like, instead of having config and state in x amount of different locations we have a single source of truth, declarative, versioned. 

Now, pulled or pushed seems to me like a detail not directly related to GitOps. 

Why is pulled highlighted so strong as a principle of GitOps?

**Comment by makkes** [comment]
[Related prior discussion on Slack](https://cloud-native.slack.com/archives/C01G9DEE88M/p1671020692512439).

**Comment by makkes** [comment]
Also, related discussion: https://github.com/open-gitops/project/discussions/134

**Comment by scottrigby** [comment]
Thanks @makkes 

@kickthemooon would like to hear your feedback after reading the points in that discussion, and also the proposed update to linking principal 3 to a new glossary item "Pull": https://github.com/open-gitops/documents/pull/65 your feedback would be valuable. Thanks!

**Comment by kickthemooon** [comment]
@scottrigby Thanks, I'll take a look and try to give feedback.

**Comment by scottrigby** [comment]
- https://github.com/open-gitops/documents/pull/65 was merged
