### ISSUE TITLE
Create `code` repo

### ISSUE THREAD

**Issue by nikimanoledaki** [open-gitops/project#163]
Hi! As part of the GitOps-EnvSus subgroup, we (@open-gitops/gitops-environmental-sustainability) would like to move some of the energy benchmark tests of Flux & ArgoCD from a personal org to OpenGitOps.

@scottrigby mentioned previously that we could create a `code` repo: https://github.com/open-gitops/project/issues/1

We would appreciate some feedback and guidance from the OpenGitOps group on the best way to do this + help with bootstrapping this repo. Thank you :)

@niklasmtj mentioned that the repo structure could be organised by initiative/subgroup. For example, we could have an `environmental-sustainability` directory.

**Comment by todaywasawesome** [comment]
Let's start with a standalone repo. We can combine later if that makes more sense 😄 

I'll set it up.

**Comment by todaywasawesome** [comment]
Repo created, the @open-gitops/gitops-environmental-sustainability team all have Maintainer access. 

https://github.com/open-gitops/environmental-sustainability
