### ISSUE TITLE
Retire William Caban as active maintainer

### ISSUE THREAD

**Issue by williamcaban** [open-gitops/project#190]
Hi OpenGitOps community,

I cannot attend the OpenGitOps community meetings anymore because of other responsibilities. Since I cannot dedicate the time the community deserves, I found it best to request to retire my name as an active maintainer or member and give the opportunity to others.

It has been great getting to meet many of you and uncover the principles of the GitOps paradigm together. It has transformed how any modern system is managed and operated.

It has been great working with @scottrigby @christianh814 @todaywasawesome @niklasmtj  See you around!

**Comment by scottrigby** [comment]
It's been great collaborating with you on this William, from the GitOps WG to the OpenGitOps CNCF project. See you around the community! 🫶 🙌
