### ISSUE TITLE
GitOps Flux Series [Virtual][Spanish]

### ISSUE THREAD

**Issue by mmorejon** [open-gitops/project#56]
Hello GitOps WG Team,

From [Sngular](https://www.sngular.com/) company we are conducting a series of chapters about GitOps - Flux2 with the aim of sharing knowledge of this methodology / technology.

The series is in Spanish and totally free. The chapters are broadcasted live on Tuesdays at 19:00 with the desire to create a space where we can talk about GitOps in Spanish. The reference links are:

[Content guide of the series](https://github.com/sngular/gitops-flux-series) and [Youtube playlist](https://www.youtube.com/playlist?list=PLuQL-CB_D1E7gRzUGlchvvmGDF1rIiWkj).

My question is: Is it possible that from this group can be supported to spread these events so that more people can benefit from this space?

**Comment by scottrigby** [comment]
Hey @mmorejon would love to follow up with you about this if you're still around and doing GitOps?

**Comment by mmorejon** [comment]
Hi @scottrigby, GitOps / Flux2 is part of our daily routines at Sngular, and the Youtube playlist has been used as training for new members of our team.
Let me know your ideas about this course in Spanish or about anything else about GitOps.

**Comment by roberthstrand** [comment]
Closing this as it seem to be a stale issue
