### ISSUE TITLE
Getting Involved

### ISSUE THREAD

**Issue by jnpacker** [open-gitops/project#69]
Hi,
I work on GitOps with Red Hat Advanced Cluster Management for Kubernetes.  We use GitOps internally to drive out entire development LifeCycle.  This spans our application all the way down to Cluster Provisioning/Configuration and maintenance (for dev's and in pipelines) / security.  One of  the products core tenants is GitOps for Clusters, Application and Security LifeCycle for all your Kuberentes clusters.

We have a number of opensource projects that allow you to perform GitOps on Local and Remote Kubernetes clusters.
https://github.com/open-cluster-management/community  We would love to present some of this in a future meeting.

I look forward to collaborating with the GitOps working group.

**Comment by christianh814** [comment]
@jnpacker Still invited to our bimonthly meeting :)
